### ISSUE TITLE
Bad link for bug report

### ISSUE THREAD

**Issue by remicollet** [GoogleCloudPlatform/stackdriver-debugger-php-extension#44]
Can you please fix the "Package Bugs" link in https://pecl.php.net/package/stackdriver_debugger

**Comment by chingor13** [comment]
Sure, but I'm not seeing how to set the link from the web UI, the pecl/pear command line, or via the `package.xml` file.

**Comment by chingor13** [comment]
Ah, I found the little pencil link. It looked like a broken image placeholder!

**Comment by chingor13** [comment]
Fixed! Thanks for the report.
